### ISSUE TITLE
Safari error

### ISSUE THREAD

**Issue by reneklacan** [one-signal/OneSignal-Website-SDK#36]
Hi there,

I'm seeing this error on Safari browser

```
TypeError: undefined is not an object (evaluating 'navigator.serviceWorker.controller') ... sdk.js:1869
```

But notification are working.

In our website we are including this js file `https://cdn.onesignal.com/sdks/OneSignalSDK.js`

Let me know if you need more info.

**Comment by jasonpang** [comment]
Hi reneklacan,

Thanks for reporting that! This should be fixed in the next release of our web SDK. Should be caused by `isPushNotificationsEnabled()` where we are calling `navigator.serviceworker.controller`.

**Comment by reneklacan** [comment]
@jasonpang Thank you very much! Any estimations when is new SDK going to be released?

**Comment by jasonpang** [comment]
Hi reneklacan,

The new SDK has been deployed :)

**Comment by reneklacan** [comment]
@jasonpang Thank you! :)

**Comment by support3ds** [comment]
Hi **@jasonpang** It seems that there still exist a relevant issue on safari only. 
Chrome and FireFox work as expected.

**OneSignalSDK.js:5373** - TypeError: undefined is not an object (evaluating 'n.css')

Configuration instruction have been followed from your website and _safari_web_id_ included.

Thanks in advance.

**Comment by jasonpang** [comment]
Hi @support3ds,

Do you have a publicly available URL that we could access to try and reproduce the error? In the past, this error would occur when a third-party library overrides Function.bind / Function.apply which affects the way our CSS for the notify button is loaded into the page. But you said it works on Chrome and Firefox without issues, so I'm not sure what the problem is.

If you don't have a publicly available URL, could you provide as detailed of a stack trace as possible? Hopefully with a column number!

**Comment by support3ds** [comment]
@jasonpang thanks for your prompt reply. Apparently, it was a missing from our side. After uploading the icon on Safari configuration it worked properly. Thanks for your time.

**Comment by jasonpang** [comment]
Glad to hear it! Closing the issue then.
